server.port: 8083

spring:
  application:
    name: market-service


  config:
    import: 'configserver:'

  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 5

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

app:
  kafka:
    url: "kafka-1:9092,kafka-2:9092,kafka-3:9092"
    group-id: market-service
    topics:
      listing-status-updated: listing-status-updated
      saved-listing-unavailable: saved-listing-unavailable
      deal-created: deal-created
      deal-confirmation: deal-confirmation
