openapi: "3.0.0"



info:
  title: 'marketplace'
  version: '1.0.0'


components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: query
      name: userId

servers:
  - url: http://localhost:8080/api/v1

paths:

  /categories:
    $ref: 'api/Category.yaml#/collection'
  /categories/{id}:
    $ref: 'api/Category.yaml#/singleton'
  /saved-listings:
    $ref: 'api/SavedListing.yaml#/collection'
  /saved-listings/{listing_id}:
    $ref: 'api/SavedListing.yaml#/singleton'
  /deal-reviews:
    $ref: 'api/DealReview.yaml#/collection'
  /deal-reviews/{id}:
    $ref: 'api/DealReview.yaml#/singleton'
  /seller-reviews:
    $ref: 'api/SellerReview.yaml#/collection'
  /seller-reviews/{seller_id}:
    $ref: 'api/SellerReview.yaml#/singleton'
  /listings:
    $ref: 'api/Listing.yaml#/collection'
  /listings/{id}:
    $ref: 'api/Listing.yaml#/singleton'
  /listings/open:
    $ref: 'api/Listing.yaml#/open'
  /listings/{id}/status:
    $ref: 'api/Listing.yaml#/status'
  /deals:
    $ref: 'api/Deal.yaml#/collection'
  /deals/{id}:
    $ref: 'api/Deal.yaml#/singleton'
  /users:
    $ref: 'api/User.yaml#/collection'
  /users/{id}:
    $ref: 'api/User.yaml#/singleton'
  /users/listings:
    $ref: 'api/Listing.yaml#/user_listings'
  /users/{user_id}/deals:
    $ref: 'api/Deal.yaml#/users_used_id_deals'