spring:
  application:
    name: monolith
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false

  cloud:
    config.uri: http://localhost:8888

  config:
    import: 'optional:configserver:http://localhost:8888'

  data:
    web:
      pageable:
        max-page-size: 50

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
