server.port: 8082

logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG

spring:
  application:
    name: listings-service

  jackson:
    property-naming-strategy: SNAKE_CASE

  r2dbc:
    url: ${DATASOURCE_URL:r2dbc:postgresql://localhost:5432/postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    username: ${DATASOURCE_USERNAME:postgres}

  liquibase:
    enabled: false

  data:
    web:
      pageable:
        max-page-size: 50

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
