server.port: 8080


spring:
  application:
    name: gateway
  config:
    import: 'configserver:'

  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 5
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/login
          filters:
            - AuthenticationFilter

        - id: market-service
          uri: lb://market-service
          predicates:
            - Path=/api/v1/deals/**, /api/v1/listings/**, /api/v1/categories/**, /api/v1/saved-listings/**
          filters:
            - AuthenticationFilter

        - id: reviews-service
          uri: lb://reviews-service
          predicates:
            - Path=/api/v1/reviews/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
