server.port: 8080

jwt:
  secret: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="

logging:
  level:
    root: debug

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthenticationFilter
