server.port: 8080

jwt:
  secret: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="

logging:
  level:
    web: debug

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: users-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/login, /api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: categories-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}