server.port: 8080

logging:
  level:
    web: debug

spring:
  application:
    name: gateway
  config:
    import: 'configserver:'

  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 5
    gateway:
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1/auth/login, /api/v1/users/**
          filters:
            - AuthenticationFilter

        - id: categories-service
          uri: lb://categories-service
          predicates:
            - Path=/api/v1/categories/**
          filters:
            - AuthenticationFilter

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
