spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false

  data:
    web:
      pageable:
        max-page-size: 50

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        slowCallDurationThreshold: 4s
        slowCallRateThreshold: 90
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 10
        ignore-exceptions:
          - feign.FeignException.FeignClientException

  timelimiter:
    configs:
      default:
        timeout-duration:
          seconds: 1
        cancel-running-future: true

logging:
  level:
    web: DEBUG
    org:
      springframework:
        security: DEBUG
