server.port: 8086

app:
  minio:
    url: ${MINIO_URL:http://127.0.0.1:9000}
    username: ${MINIO_USERNAME:user}
    password: ${MINIO_PASSWORD:password}
    bucket: images

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: image-service

  config:
    import: 'configserver:'

  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 5

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
